### ISSUE TITLE
mvn compile fails

### ISSUE THREAD

**Issue by giusepperizzo** [dexter/dexter#2]
Hi, starting from a clean copy (git clone) the mvn compile fails, it seems that external projects/libraries are not linked in the main pom.xml.

**Comment by tgalery** [comment]
Hi @giusepperizzo I had the same problem. In my case, it turned out that to be an error with the maven version that comes with ubuntu and how it reads the apache.commons.lang specification in the pom. I updated mvn to the newest verstion from apache and it compiled. @diegoceccarelli it might be worth updating the readme with this ? If you think so, I'm happy to send a PR.

**Comment by diegoceccarelli** [comment]
Please @tgalery  do that! Thanks!

**Comment by strani** [comment]
I think this issue can be closed since the additional details provided in the README.
