### ISSUE TITLE
Unexpected error in dexter-core script generate-spots.sh

### ISSUE THREAD

**Issue by davidTamayo** [dexter/dexter#24]
The execution of generate-spots.sh entails several errors. Although I’ve not checking I would say there’s an error for each article in Wikipedia, no matter the codification of its title:

2016-08-16 13:19:06,857 20252 [main] INFO  it.cnr.isti.hpc.dexter.cli.spot.ExtractSpotsCLI - cannot find id for label Corriente_de_Groenlandia
2016-08-16 13:19:06,857 20252 [main] INFO  it.cnr.isti.hpc.dexter.cli.spot.ExtractSpotsCLI - cannot find id for label Corriente_de_las_Kuriles

Although I’ve continued running the rest of the scripts to compile Dexter, the results that I achieved at the end are not good at all. For example, it identifies entities such as “la” or “el”, which mean “the” and have no other meaning.

I have two questions:

a) The bad quality of the results may be due to the errors that I get when running generate-spots.sh?
b) How can I avoid these type of errors?

**Comment by diegoceccarelli** [comment]
`"cannot find id for label"` are infos, and they are not errors, on wikipedia you can have anchors that do not point to any page (Wikipedia highlights them in Red), so it can happen that for a label (i.e., an anchor) Dexter cannot find an id.
I print them just to check if I don't find an Id for a 'good' label (note that sometimes the problem is that who put the link, put the name of the target page with a typo, or a letter in the wrong case.. these are still considered errors), so I would say that a) no. 

la, or el, should be filtered out using the link probability, i.e, number of times that the label appears as a link divided the number of times that the label appears as simple text. la or el should have a low link probability and dexter should filter them based on that. Can you check how much is the link probability using the interface? (the `spot` api returns it) 

maybe you just need to increase it, at the moment it is set based on the English that has more articles.

**Comment by rschwab68** [comment]
> Although I’ve continued running the rest of the scripts to compile Dexter, the results that I achieved at the end are not good at all. For example, it identifies entities such as “la” or “el”, which mean “the” and have no other meaning.

common words should be filtered out by link probability filter. they occur often in wikipedia but are not linked often.
you are using the standard filter?
your spanish dexter model is online and accessible?

**Comment by davidTamayo** [comment]
Modifying the lp we have improved the results. (lp =0.4, spanish)

@rschwab68 , at the moment I'm running it on localhost, If I have more issues I will try to put it accessible. 

Thanks!
